/*
Compares two strings and checks if they are equivalent up to character l
*/
int cmp_string(char *str, char *cmp, int length) {
    for (int i = 0; i < length; i++) {
        if (str[i] != cmp[i]) {
            return 0;
        }
    }
    return 1;
}

/*
Extracts an integer from a string
The following function (lines 18 to 39) was generated by Microsoft Copilot.
*/
int get_flag_value(char *str) {
    int num = 0;
    int found = 0;
    int negative = 0;

    while (*str) {
        if (*str == '-' && (*(str+1) >= '0' && *(str+1) <= '9')) {
            negative = 1;
        }
        if (*str >= '0' && *str <= '9') {
            num = num * 10 + (*str - '0');
            found = 1;
        } else {
            if (found) {
                break;
            }
        }
        str++;
    }
    
    if (negative) {num = -num;}

    return num;
}