#include <stdio.h>
#include <stdlib.h>
#define true 1
#define false 0

/*
compares two strings and checks if they are equivalent up to character l
*/
int cmp_string(char *str, char *cmp, int length) {
    for (int i = 0; i < length; i++) {
        if (str[i] != cmp[i]) {
            return false;
        }
    }
    return true;
}

/*
Extracts an integer from a string
The following function (lines 23 to 38) was generated by Microsoft Copilot.
*/
int get_flag_value(char *str) {
    int num = 0;
    int found = 0;

    while (*str) {
        if (*str >= '0' && *str <= '9') {
            num = num * 10 + (*str - '0');
            found = 1;
        } else {
            if (found) {
                break;
            }
        }
        str++;
    }

    return num;
}